<template>
    <div>
        <b-container>
            <b-row>
                <b-col>
                    <h1>Church</h1>
                </b-col>
            </b-row>
        </b-container>
    </div>
</template>
